server:
  port: 8088
  ssl:
    key-store: classpath:shichengtai.xyz.jks
    key-store-password: njlh92v715
    key-store-type: JKS
  servlet:
    context-path: /
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dbmeiye?serverTimezone=Asia/Shanghai
    username: root
    password: root
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 50s
    database: 0
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: 10000
        max-idle: 30
        min-idle: 10

mybatis-plus:
  #  global-config:
  #    db-config:
  #      id-type: auto
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #mapper-locations: classpath:mybatis/mapper/*.xml
  global-config:
    db-config:
      logic-delete-field: flag # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

oss:
  qiniu:
    domain: com.shichengtai.xyz # 访问域名(默认使用七牛云测试域名)
    accessKey: BkxIAgbT4E5CZl2og1uOwsAT6oV8tO2lFW0j_lti # 公钥 刚才的AK
    secretKey: K97K5CLZEdB4CWBaIc5xXxsyWBmue9Xpxe9u_uvh # 私钥 刚才的SK
    bucketName: sctlqq  #存储空间名称

jwt:
  #  https://tool.ip138.com/random/   获取随机key
  key: Qd#TzdP&q!5hpG(#af4FEtB_ROzsEXQgX72KRo_PJES%3oA^%V4aas(chi@Ri2ZNUpx@jByxIeVYQj&RAA7XgmACXy5)
  expiration: 86400000 #24h

wx:
  appid: wx10f5a4e50fb71944
  js_code: 09227c7470050c2e6de97272447ee88f

